// <auto-generated />
using LearningCoding.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LearningCoding.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LearningCoding.Models.ProgrammingLanguage", b =>
                {
                    b.Property<int>("ProgrammingLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProgrammingLanguageCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgrammingLanguageCons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgrammingLanguageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgrammingLanguageHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgrammingLanguageImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgrammingLanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgrammingLanguageOverview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgrammingLanguagePros")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgrammingLanguageId");

                    b.ToTable("ProgrammingLanguage");
                });
#pragma warning restore 612, 618
        }
    }
}
